<center><h1>Pytorch Intro</h1></center>

<h2>Tensors Handling</h2>

Firstly, we import the library

In [1]:
import torch
import numpy as np

Afterwards we do some operations

In [2]:
#Creating an empty(uninitialized) 3x3 tensor
tensor1 = torch.empty((3,3), dtype=torch.double) # Can be also written without the tuple
print('Empty Tensor=', tensor1)

#Creating 4D column tensor of zeros
tensor2 = torch.zeros(4,1, dtype=torch.double)
print()
print(tensor2)

#Creating 3x4 tensor of ones
tensor3 = torch.ones(3,4, dtype=torch.double)
print()
print(tensor3)

#Multiplying tensor3 and tensor4 like in linear algebra
#(should result a 3x1 tensor), mul does element wise multiplication
# or with a scalar
tensor4 = torch.matmul(tensor3, tensor2)
print()
print(tensor4)
print(tensor4.size())

#Converting a list of lists to tensor
print()
print(torch.tensor([[1,23],[3,45]]))

#Converting a tensor to numpy array
print()
tensor4_np = tensor4.numpy()
print('Tensor 4 numpy type=', type(tensor4_np))

#Converting a numpy array to tensor
print()
tensor4_torch = torch.from_numpy(tensor4_np)
print('Tensor 4 torch type=', type(tensor4_torch))
print('Are equal=', torch.equal(tensor4_torch, tensor4))

Empty Tensor= tensor([[6.9674e+252, 3.5825e+246, 2.6306e+267],
        [7.0738e+194, 2.6825e-260,  2.1632e-27],
        [ 1.8773e-09, 2.3253e+251, 2.5840e+161]], dtype=torch.float64)

tensor([[0.],
        [0.],
        [0.],
        [0.]], dtype=torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

tensor([[0.],
        [0.],
        [0.]], dtype=torch.float64)
torch.Size([3, 1])

tensor([[ 1, 23],
        [ 3, 45]])

Tensor 4 numpy type= <class 'numpy.ndarray'>

Tensor 4 torch type= <class 'torch.Tensor'>
Are equal= True


Now that we saw some basic operation we will implement some vector functions

In [3]:
def dot_product(t1, t2):
    return int(torch.matmul(t1, t2))

def square_vector(t):
    return torch.mul(t, t)

def r2_score(y_true, y_pred):
    # SS_res = Sum_i((y_true_i - y_pred_i)^2)
    # alpha is the scalar of 2nd arg
    # You can use torch.square
    SS_res = torch.sum(torch.square(torch.sub(y_true, y_pred, alpha=1)))
    # SS_tot = Sum_i((y_true_i - mean(y_true))^2)
    SS_tot = torch.sum(square_vector(torch.sub(y_true, torch.mean(y_true))))
    
    return float(1 - (SS_res / SS_tot))

#Testing
t1 = torch.tensor([2,1,4,6])
t2 = torch.tensor([1,2,3,4])

#Should be 40
print('Dot product is', dot_product(t1, t2))

# Should be [4,1,16,36]
print('Square tensor is', square_vector(t1))

t1 = torch.tensor([2,3,2,2], dtype=torch.double)
t2 = torch.tensor([2,3,2,2], dtype=torch.double)
print('R^2 is', r2_score(t1, t2))

Dot product is 40
Square tensor is tensor([ 4,  1, 16, 36])
R^2 is 1.0



Note that, that we wrote different functions using tensor operations other than
the ones that we presented to the 2<sup>nd</sup> cell.
So, anytime you want to do something specific with tensors look in the documentation
at https://pytorch.org/docs/stable/torch.html.